import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../../index.html',import.meta.url),'utf8');
const nav=readFileSync(new URL('../../app-navigation.js',import.meta.url),'utf8');
const fn=name=>{const start=html.indexOf('function '+name+'(');assert.ok(start>=0,name);return html.slice(start,html.indexOf('\nfunction ',start+1));};
function navigation(){
 const calls=[];const c={currentUser:{uid:'staff'},currentAccessMode:'staff',currentAccessKey:'',isStaffUser:()=>true,isAdminUser:()=>true,confirmBeforeLeavingScreen:f=>f(),hideAllAppScreens(){},document:{getElementById:()=>({style:{}})},showAppSection:s=>calls.push(s)};
 for(const name of ['showMain','showUrlEntry','showManualNewsBrief','showManualLongView','showPodcastPrepDashboard','showStaffGuestWriterStories','showGuestWriterDashboard','showScratchChoice'])c[name]=()=>calls.push(name);
 c.window=c;vm.createContext(c);vm.runInContext(nav,c);return {c,calls};
}
for(const [name,fallback] of [['showUrlEntry','draft'],['showMain','draft'],['showManualNewsBrief','draft'],['showManualLongView','draft']])test(name+' Back restores Draft, including direct entry',()=>{
 const {c,calls}=navigation();c.showAppSection('draft');c[name]();c.goBackInApp(fallback);assert.equal(calls.at(-1),'draft');
 c.resetAppBackNavigation();c[name]();c.goBackInApp(fallback);assert.equal(calls.at(-1),'draft');
});
test('Back restores previous internal context instead of always Home',()=>{const {c,calls}=navigation();c.showMain();c.showUrlEntry();c.goBackInApp('draft');assert.equal(calls.at(-1),'showMain');});
test('detail Back preserves Podcast and Guest Writer list context',()=>{for(const [name,key]of [['showPodcastPrepDashboard','podcast-list'],['showStaffGuestWriterStories','writer-stories']]){const {c,calls}=navigation();c.showAppSection('home');c[name]();c.goBackInApp(key,true);assert.equal(calls.at(-1),name);}});
test('Back rejects external/auth targets and clears prior roles',()=>{const {c,calls}=navigation();c.showAppSection('draft');c.showUrlEntry();const n=calls.length;c.goBackInApp('https://example.com');c.goBackInApp('login');assert.equal(calls.length,n);c.currentAccessMode='guest_writer';c.currentUser={uid:'writer'};c.goBackInApp('draft');assert.equal(calls.at(-1),'showGuestWriterDashboard');assert.doesNotMatch(nav,/history\.back|location\.(?:href|assign)/);});
test('cancelled leave preserves history and form screen',()=>{const {c,calls}=navigation();c.showAppSection('draft');c.showUrlEntry();c.confirmBeforeLeavingScreen=()=>{};c.goBackInApp('draft');assert.equal(calls.at(-1),'showUrlEntry');c.confirmBeforeLeavingScreen=f=>f();c.goBackInApp('draft');assert.equal(calls.at(-1),'draft');});
test('manual long-view has shared Back and workflow has no redundant Home',()=>{assert.match(html,/<button class="app-back-link" onclick="goBackInApp\('draft'\)">&larr; Back<\/button>\s*<h2>Manual long-view story/);assert.doesNotMatch(html,/onclick="goWorkflowHome\(\)"/);});
function storyContext(existing,staff=true){
 let patch;const c={currentUser:{uid:'writer'},isStaffUser:()=>staff,firebase:{firestore:{FieldValue:{serverTimestamp:()=> 'SERVER_TIME'}}},db:{collection:()=>({doc:()=>({})}),runTransaction:f=>f({get:async()=>({exists:true,data:()=>existing}),update:(_,p)=>{patch=p}})}};
 vm.createContext(c);vm.runInContext(fn('guestWriterCanWrite')+fn('updateGuestWriterArticle')+fn('guestWriterStatusChangedDate')+fn('guestWriterStatusChangedMeta'),c);return {c,patch:()=>patch};
}
test('actual transition stamps server time; same-status edits preserve timestamp',async()=>{const {c,patch}=storyContext({sourceType:'guest_writer',status:'idea_under_review'});await c.updateGuestWriterArticle('a',{status:'draft',writingUnlocked:true});assert.equal(patch().statusChangedAt,'SERVER_TIME');const second=storyContext({sourceType:'guest_writer',status:'draft',statusChangedAt:'OLD'});await second.c.updateGuestWriterArticle('a',{status:'draft',body:'Edited',statusChangedAt:'FORGED'});assert.equal('statusChangedAt' in second.patch(),false);});
test('writer cannot self-approve or modify preapproval content, but approved draft saves and submits',async()=>{const blocked=storyContext({sourceType:'guest_writer',writerUid:'writer',status:'idea_under_review'},false);await assert.rejects(blocked.c.updateGuestWriterArticle('a',{status:'draft'}),/not open/);const approved=storyContext({sourceType:'guest_writer',writerUid:'writer',status:'draft'},false);await approved.c.updateGuestWriterArticle('a',{status:'draft',body:'Writing'});assert.equal('statusChangedAt' in approved.patch(),false);await approved.c.updateGuestWriterArticle('a',{status:'under_review'});assert.equal(approved.patch().statusChangedAt,'SERVER_TIME');await assert.rejects(approved.c.updateGuestWriterArticle('a',{status:'published'}),/cannot change approval/);});
test('existing timestamps are honest: approval event is used; updatedAt is never used',()=>{const {c}=storyContext({});assert.equal(c.guestWriterStatusChangedDate({status:'draft',updatedAt:123}),null);assert.equal(c.guestWriterStatusChangedMeta({status:'draft',updatedAt:123}),'Status change date unavailable');assert.equal(c.guestWriterStatusChangedDate({status:'draft',ideaStatus:'approved',ideaApprovedAt:123}),123);assert.equal(c.guestWriterStatusChangedDate({status:'draft',statusChangedAt:456,ideaApprovedAt:123}),456);assert.match(fn('openStaffGuestWriterStory'),/guestWriterStatusChangedMeta\(story\)/);});
test('Start writing is draft; draft/revision route to editors and review stays blocked',()=>{const calls=[];const c={showSubmitStoryIdeaScreen:()=>calls.push('idea'),showIdeaDiscussionScreen:()=>calls.push('discussion'),openGuestWriterRevisionScreen:()=>calls.push('revision'),showGuestWriterStoryStatus:()=>calls.push('review'),hasGeneratedGuestWriterDraft:()=>false,openGuestWriterWritingScreen:()=>calls.push('write'),openGuestWriterGeneratedDraftWorkflow:()=>calls.push('generated')};vm.createContext(c);vm.runInContext(fn('guestWriterCanWrite')+fn('routeGuestWriterStoryStage')+fn('guestWriterStatusLabel'),c);assert.equal(c.guestWriterStatusLabel('draft'),'Start writing');c.routeGuestWriterStoryStage({status:'draft',writingUnlocked:false,locked:true});assert.equal(calls.at(-1),'write');for(const status of ['under_review','submitted','scheduled','published']){c.routeGuestWriterStoryStage({status,writingUnlocked:true});assert.equal(calls.at(-1),'review');}c.routeGuestWriterStoryStage({status:'idea_under_review'});assert.equal(calls.at(-1),'discussion');c.routeGuestWriterStoryStage({status:'changes_requested'});assert.equal(calls.at(-1),'revision');});
test('opening a cached preapproval story fetches the authoritative approved record',async()=>{let opened;const c={currentUser:{uid:'writer'},currentAccessMode:'guest_writer',db:{collection:()=>({doc:()=>({get:async()=>({exists:true,id:'a',data:()=>({sourceType:'guest_writer',writerUid:'writer',status:'draft'})})})})},updateGuestWriterStoryCaches(){},routeGuestWriterStoryStage:s=>opened=s,alert:m=>{throw Error(m)}};vm.createContext(c);vm.runInContext(fn('viewGuestWriterStory'),c);await c.viewGuestWriterStory('a');assert.equal(opened.status,'draft');});
test('all Guest Writer status mutation entry points use the central transition helper',()=>{for(const name of ['approveGuestWriterIdea','askGuestWriterIdeaChanges','sendStoryChangeRequest','submitGuestWriterStoryAsIs','saveGuestWriterDraft','markStaffItemAsPublished'])assert.match(fn(name),/updateGuestWriterArticle\(/,name);assert.match(fn('submitGuestWriterIdea'),/statusChangedAt: firebase.firestore.FieldValue.serverTimestamp\(\)/);assert.match(fn('approveGuestWriterIdea'),/if \(!isStaffUser\(currentUser\)\) return/);});
